
services:
  foundry-node-1:
    image: ghcr.io/foundry-rs/foundry:latest
    entrypoint: ["anvil", "--host", "0.0.0.0"]
    ports:
      - "8545:8545"
    volumes:
      - C:/Users/Nucle/Documents/my-foundry-project:/app
    working_dir: /app

  foundry-node-2:
    image: ghcr.io/foundry-rs/foundry:latest
    entrypoint: ["anvil", "--host", "0.0.0.0"]
    ports:
      - "8546:8545"
    volumes:
      - C:/Users/Nucle/Documents/my-foundry-project:/app
    working_dir: /app